### ISSUE TITLE
Errors during nulling semantics → Can't locate g1_symbol_display() method

### ISSUE THREAD

**Issue by latk** [jeffreykegler/Marpa--R3#43]
When an error occurs during semantics, the error is wrapped by Marpa with more context. This fails when nulling semantics are evaluated.

Code to reproduce:

``` perl
use Marpa::R3 4.001_050;
Marpa::R3::Scanless::G->new({ source => \q{ A ::= action => main::semantics } })->parse(\"");
sub semantics { die "argh" }
```

Actual error message:

```
Can't locate object method "g1_symbol_display" via package "Marpa::R3::Scanless::G" at $PERL5LIB/Marpa/R3/SLV.pm line 394.
Marpa::R3 exception at test.pl line 2.
```

Expected error message:

```
============================================================
* THE MARPA SEMANTICS PRODUCED A FATAL ERROR
* THIS IS WHAT MARPA WAS DOING WHEN THE PROBLEM OCCURRED:
Computing value for null symbol: A
* THIS WAS THE FATAL ERROR MESSAGE:
argh at test.pl line 3.
```

Apparently that method was renamed? There are also a few uses of the method in `SLG.pm`.

**Comment by jeffreykegler** [comment]
@latk Could you check that this commit fixes the problem?  Note that between your version (the last CPAN developer release) and the above commit, I did a massive renaming so that Marpa::R3::Scanless::G is now Marpa::R3::Grammar.  If you use this commit as a patch, I think the name change may not make a difference, but it is something to watch for.
